### ISSUE TITLE
Update the wgpu library to 0.19.4

### ISSUE THREAD

**Issue by VarLad** [JuliaWGPU/WGPUNative.jl#16]
@arhik Can you update the bindings to the latest released version (0.19.4 at the time of writing)?

**Comment by arhik** [comment]
I am on break. I will push it in two days.

**Comment by arhik** [comment]
@VarLad I just pushed it. I also instructions on how to do it here -> https://github.com/JuliaWGPU/WGPUNative.jl/blob/main/syncUpstream.md

**Comment by VarLad** [comment]
Thanks a lot!
